### ISSUE TITLE
Venga, subid algo al repo

### ISSUE THREAD

**Issue by Makova** [oslugr/campus15#3]
El resto de profesores en los grupos mayores y pequeños, id subiendo algo al repo, esto nos servirá para otros Campus. De echo en este hay cosas del Campus14, imágenes, link, etc...

**Comment by germaaan** [comment]
Estoy precisamente en ello, pensando cosas que poner.

**Comment by germaaan** [comment]
Yo voy a aprovechar los ejercicios de @toblerone554 de ofimática y HTML como base, aumentar la dificultad un poco en algunos y además añadir algo más de las cosas "extras" que había pensando dar.

**Comment by oslugr** [comment]
Pues esos extras nos vendrán bien para el grupo de medianos :+1:

**Comment by renatolrr** [comment]
Voy poniendo algo en el proyecto 2. Pero estoy fatal de tiempo. 
Luego amplio información.

**Comment by molocohb** [comment]
¿En CV_Proyectos_profesores subimos cada uno nuestros proyectos? No pillo bien cómo lo estáis haciendo.

**Comment by Makova** [comment]
No, eso ya esta así.

## 

Makova

**Comment by renatolrr** [comment]
En CV_Proyectos_profesores  he puesto enlace a la carpeta Poyectos/Proyecto2.
Y he añadido una posible solución, en dicha carpeta.
