### ISSUE TITLE
Me pongo con AppInventor

### ISSUE THREAD

**Issue by Makova** [oslugr/campus15#5]
José Alonso, me voy a poner con AppInventor a ver si se puede añadir más screen sin tener que meter todos los bloques de nuevo, o encuentro algo para que puedan cambiar de dibujo y seguir coloreando. He pensado en dibujos menos infantiles como, Goku, Bejeta, Batman, etc...
También quiero dejar el juego del meteorito finalizado, con tres vidas una vez toque el meteorito detrás de la nave y solucionar la fluidez de la nave para subir bajar.

**Comment by germaaan** [comment]
El tema de la que nave suba y baje bien es cambiar en el "when Canvas1.Dragged do" el "call nave.MoveTo y get startY" a "call nave.MoveTo y get currentY". Lo estuve probando el otro día y lo arreglé así, pero es que con tanto lío se me había pasado subirlo.

**Comment by Makova** [comment]
Muchas gracias, Germán :+1:

**Comment by Makova** [comment]
Estoy a ver si cuando el meteorito toca la nave se acaba la partida con "Game Over", o darle 3 vidas más antes de palmarla.

**Comment by oslugr** [comment]
Cierro esto.
